### ISSUE TITLE
Issue on uploading file on eshop-mongodb

### ISSUE THREAD

**Issue by Lazhari** [totaljs/eshop#21]
Hi, 
when I try to upload a file on admin space, I get this error
```
manager ---> TypeError: GridStore.writeFile is not a function (http://localhost:8000/manager/upload/) TypeError: GridStore.writeFile is not a function
    at Array.<anonymous> (/Users/macbookproretina13/Projects/data-exports/eshop-db/eshop-master/eshop-mongodb/controllers/manager.js:101:13)
    at Array.wait.Array.waitFor (/Users/macbookproretina13/Projects/data-exports/eshop-db/eshop-master/eshop-mongodb/node_modules/total.js/utils.js:4301:9)
    at Object.upload (/Users/macbookproretina13/Projects/data-exports/eshop-db/eshop-master/eshop-mongodb/controllers/manager.js:89:13)
    at Subscribe.doExecute (/Users/macbookproretina13/Projects/data-exports/eshop-db/eshop-master/eshop-mongodb/node_modules/total.js/index.js:9590:23)
    at Subscribe.execute (/Users/macbookproretina13/Projects/data-exports/eshop-db/eshop-master/eshop-mongodb/node_modules/total.js/index.js:9516:8)
    at Subscribe.doAuthorization (/Users/macbookproretina13/Projects/data-exports/eshop-db/eshop-master/eshop-mongodb/node_modules/total.js/index.js:9618:9)
    at /Users/macbookproretina13/Projects/data-exports/eshop-db/eshop-master/eshop-mongodb/node_modules/total.js/index.js:9543:9
    at F.onAuthorize (/Users/macbookproretina13/Projects/data-exports/eshop-db/eshop-master/eshop-mongodb/models/users.js:411:3)
    at Subscribe.prepare (/Users/macbookproretina13/Projects/data-exports/eshop-db/eshop-master/eshop-mongodb/node_modules/total.js/index.js:9530:3)
    at Subscribe.doEnd (/Users/macbookproretina13/Projects/data-exports/eshop-db/eshop-master/eshop-mongodb/node_modules/total.js/index.js:9669:8)
```
I use different Mongodb driver version but I get the same error all time.

**Comment by petersirka** [comment]
Hi @Lazhari, there is a bug - otherwise MongoDB driver changes implementation of GridStore (shit). I'll fix it this week. Thank you.

**Comment by petersirka** [comment]
Hi @Lazhari, I have fixed the problem. Please download again `eshop/mongodb` from GitHub and update `sqlagent` throught NPM `$ npm install sqlagent`.

Thank you!

**Comment by Lazhari** [comment]
Thank you @petersirka. now upload files work well
