### ISSUE TITLE
can't set custom post and custom ip

### ISSUE THREAD

**Issue by 2pay** [totaljs/eshop#24]
In release.js i set custom port and ip:

```
options.port = process.env.OPENSHIFT_NODEJS_PORT || 8080;
options.ip = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1';
```
but it not work for me.

**Comment by petersirka** [comment]
Hi @2pay,
show how me the output from console.

Thank you.

**Comment by 2pay** [comment]
I create file server.js and copy all content in release.js to it. I modified custom port and ip addresss. 

    ```
#!/bin/env node
    'use strict';
    
    var fs = require('fs');
    var options = {};
    
    //options.ip = '127.0.0.1';
    //options.port = parseInt(process.argv[2]);
    options.port = process.env.OPENSHIFT_NODEJS_PORT || parseInt(process.argv[2]);
    options.ip = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1';
    //options.config = { name: 'total.js' };
    // options.https = { key: fs.readFileSync('keys/agent2-key.pem'), cert: fs.readFileSync('keys/agent2-cert.pem')};
    
    /**
     * Release notes:
     */
    
    require('total.js').http('release', options);
```

and my logs when devploy to openshift:

    ```
remote: Preparing build for deployment
    remote: Deployment id is 3511912a
    remote: Activating deployment
    remote: Starting NodeJS cartridge
    remote: Sat Dec 24 2016 04:27:07 GMT-0500 (EST): Starting application 'eshop' ...
    remote: Waiting for application port (8080) become available ...
    remote: Application 'eshop' failed to start (port 8080 not available)
    remote: -------------------------
    remote: Git Post-Receive Result: failure
    remote: Activation status: failure
    remote: Activation failed for the following gears:
    remote: my-app-id (Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/openshift/my-app-id/nodejs
    remote: #<IO:0x000000023ce388>
    remote: #<IO:0x000000023ce310>
    remote: )
    remote: Deployment completed with status: failure
    remote: postreceive failed
    To ssh://eshop-vnclub.rhcloud.com/~/git/eshop.git/
       14e63c4..c11c149  master -> master
```

My logs on openshift:

   ```
 at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/var/lib/openshift/585df0240c1e66826e0001f2/app-root/runtime/repo/server.js:18:1)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
    DEBUG: Program node server.js exited with code 8
    DEBUG: Starting child process with 'node server.js'
```

**Comment by petersirka** [comment]
Try to replace:

```javascript
// options.port = process.env.OPENSHIFT_NODEJS_PORT || parseInt(process.argv[2]);
options.port = process.env.OPENSHIFT_NODEJS_PORT || 8080;
```

Give me a feedback.

**Comment by 2pay** [comment]
Error again, 

This is other project and it working on openshift:

```
#!/usr/bin/env node

var app = require('./app');
var debug = require('debug')('wefuny:server');
var http = require('http');

var port = normalizePort(process.env.OPENSHIFT_NODEJS_PORT || '3000');
var ip = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1';

app.set('port', port);

var server = http.createServer(app);

server.listen(port, ip);
server.on('error', onError);
server.on('listening', onListening);

function normalizePort(val) {
    var port = parseInt(val, 10);
    if (isNaN(port)) {
        return val;
    }
    if (port >= 0) {
        return port;
    }
    return false;
}

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
    var addr = server.address();
    var bind = typeof addr === 'string'
        ? 'pipe ' + addr
        : 'port ' + addr.port;
    debug('Listening on ' + bind);
}
```

**Comment by molda** [comment]
Hi @2pay 

I would recommend you to use custom cartridge https://github.com/icflorescu/openshift-cartridge-nodejs
since the default one uses node.js v0.10.x and this version causes an error due to usage of `const` in strict mode.

With the custom cartridge you get latest node.js and npm versions, if those are not the versions you want there's a way to use other versions, but i didn't go that far to figure out how to do that.

Once i used the custom cartridge i managed to get it working with bellow options:

```
options.port = process.env.NODE_PORT || 3000;
options.ip = process.env.NODE_IP || 'localhost';
```

Hope it helps.
