### ISSUE TITLE
It seems there is a missing requirement "gm"

### ISSUE THREAD

**Issue by mingodad** [totaljs/eshop#34]
Hello !
I'm trying out the eshop application and it shows errors trying to execute "gm" probably graphics-magic ?
```
c/A_frameworks/totaljs/eshop/tmp/images-small-1611262223Tpu112.jpg +profile "*" -filter "Box" -thumbnail "200x150" -limit memory 450 -limit map 900 -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 /home/mingo/dev/c/A_frameworks/totaljs/eshop/tmp/images-small-1611262223Tpu112.jpg
/bin/sh: 1: gm: not found
 (http://127.0.0.1:8000/images/small/1611262223Tpu112.jpg) Error: Command failed: gm -convert /home/mingo/dev/c/A_frameworks/totaljs/eshop/tmp/images-small-1611262223Tpu112.jpg +profile "*" -filter "Box" -thumbnail "200x150" -limit memory 450 -limit map 900 -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 /home/mingo/dev/c/A_frameworks/totaljs/eshop/tmp/images-small-1611262223Tpu112.jpg
/bin/sh: 1: gm: not found

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by petersirka** [comment]
Hi @mingodad,
you have to install `GraphicsMagick` (or ImageMagick). The eshop uses it for resizing pictures.

**Comment by mingodad** [comment]
Yes that's what I was thinking probably is a good ide to add it to the readme so other people will be able to have a clean first run after install.
Cheers !

**Comment by petersirka** [comment]
Omg I'm fool. I'll add it.
Thank you!
