### ISSUE TITLE
gm convert: Memory allocation error [File exists]

### ISSUE THREAD

**Issue by fl4x** [totaljs/eshop#58]
I have tried to run project both on Windows and Linux (I thought it was the trouble with GraphicsMagick system), but I am getting the same errors

```
======= 2019-06-25 21:00:53: Error: Command failed: gm -convert '/home/ubuntu/Downloads/gg/tmp/images-small-1611262202Tkvs19.jpg' +profile '*' -limit map 900 -limit memory 450 -thumbnail '200x150' -filter 'Hamming' -extent 0x0 -background 'white' -gravity 'Center' -extent '200x150' -quality 90 '/home/ubuntu/Downloads/gg/tmp/images-small-1611262202Tkvs19.jpg'
gm convert: Memory allocation failed (/home/ubuntu/Downloads/gg/tmp/images-small-1611262202Tkvs19.jpg) [File exists].
 (http://localhost:8000/images/small/1611262202Tkvs19.jpg) Error: Command failed: gm -convert '/home/ubuntu/Downloads/gg/tmp/images-small-1611262202Tkvs19.jpg' +profile '*' -limit map 900 -limit memory 450 -thumbnail '200x150' -filter 'Hamming' -extent 0x0 -background 'white' -gravity 'Center' -extent '200x150' -quality 90 '/home/ubuntu/Downloads/gg/tmp/images-small-1611262202Tkvs19.jpg'
gm convert: Memory allocation failed (/home/ubuntu/Downloads/gg/tmp/images-small-1611262202Tkvs19.jpg) [File exists].
    at ChildProcess.exithandler (child_process.js:290:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12)
======= 2019-06-25 21:01:19: Error: Command failed: gm -convert '/home/ubuntu/Downloads/gg/tmp/images-small-1611262202Tkvs19.jpg' +profile '*' -limit map 900 -limit memory 450 -thumbnail '200x150' -filter 'Hamming' -extent 0x0 -background 'white' -gravity 'Center' -extent '200x150' -quality 90 '/home/ubuntu/Downloads/gg/tmp/images-small-1611262202Tkvs19.jpg'
gm convert: Memory allocation failed (/home/ubuntu/Downloads/gg/tmp/images-small-1611262202Tkvs19.jpg) [File exists].
 (http://localhost:8000/images/small/1611262202Tkvs19.jpg) Error: Command failed: gm -convert '/home/ubuntu/Downloads/gg/tmp/images-small-1611262202Tkvs19.jpg' +profile '*' -limit map 900 -limit memory 450 -thumbnail '200x150' -filter 'Hamming' -extent 0x0 -background 'white' -gravity 'Center' -extent '200x150' -quality 90 '/home/ubuntu/Downloads/gg/tmp/images-small-1611262202Tkvs19.jpg'
gm convert: Memory allocation failed (/home/ubuntu/Downloads/gg/tmp/images-small-1611262202Tkvs19.jpg) [File exists].
    at ChildProcess.exithandler (child_process.js:290:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
======= 2019-06-25 21:01:29: Error: Command failed: gm -convert '/home/ubuntu/Downloads/gg/tmp/images-small-1611271007Twyhfp.jpg' +profile '*' -limit map 900 -limit memory 450 -thumbnail '200x150' -filter 'Hamming' -extent 0x0 -background 'white' -gravity 'Center' -extent '200x150' -quality 90 '/home/ubuntu/Downloads/gg/tmp/images-small-1611271007Twyhfp.jpg'
gm convert: Memory allocation failed (/home/ubuntu/Downloads/gg/tmp/images-small-1611271007Twyhfp.jpg) [File exists].
 (http://localhost:8000/images/small/1611271007Twyhfp.jpg) Error: Command failed: gm -convert '/home/ubuntu/Downloads/gg/tmp/images-small-1611271007Twyhfp.jpg' +profile '*' -limit map 900 -limit memory 450 -thumbnail '200x150' -filter 'Hamming' -extent 0x0 -background 'white' -gravity 'Center' -extent '200x150' -quality 90 '/home/ubuntu/Downloads/gg/tmp/images-small-1611271007Twyhfp.jpg'
gm convert: Memory allocation failed (/home/ubuntu/Downloads/gg/tmp/images-small-1611271007Twyhfp.jpg) [File exists].
    at ChildProcess.exithandler (child_process.js:290:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12)
```
What am I doing wrong?

**Comment by petersirka** [comment]
Hi @fl4x,

- How much RAM is free on your server?
- Which version of GraphicsMagick are you using? 
- Have you tried a default version of Eshop or do you have own version with other images?

Thx.

**Comment by fl4x** [comment]
- 16gb of RAM (12 free)
- GraphicsMagick  v1.3.32
- I am trying to run a default version of Eshop

Only some of images are loaded and errors above are thrown for every iamge on a page
![image](https://user-images.githubusercontent.com/10885321/60138323-99b10980-97b2-11e9-9858-e2c697e4ac81.png)

**Comment by petersirka** [comment]
Hmm, I have installed latest update of GM via `brew` and my version is v1.3.31 only.

Can you update a bit source-code of Eshop?

- open: __`controllers/files.js`__
- add under each `res.image(filename, function(image) {` this line of code:

```javascript
res.image(filename, function(image) {
     // THE LINE BELOW ONLY:
     image.islimit = true;
     // ...
     // ...
     // ...
     // ...
     // ...
});
```

Total.js limits the memory for images because GM/IM was a very critical part of app in some weaker machines. Please let me know if it works. I'll try to install GM today on my VM with W10.

**Comment by fl4x** [comment]
Great thanks man! This fixed the issue!

Really strange behavior, I had this kind of trouble on Windows 10 and Linux only. My Mac OS on VM was performing correctly.

**Comment by petersirka** [comment]
I have modified Total.js framework, now it doesn't use a memory limit by default.
